import { z } from "zod";
import { FacingDirection, FurnishingType, PriceUnit, PropertyStatus, PublishStatus } from "@prisma/client";

export const propertySchema = z.object({
  body: z.object({
    title: z.string().trim().min(5).max(200),
    projectId: z.string().optional(),
    builderId: z.string().optional(),
    locationId: z.string().min(1, "locationId is required"),
    propertyTypeId: z.string().min(1, "propertyTypeId is required"),
    categoryId: z.string().min(1, "categoryId is required"),
    purposeId: z.string().min(1, "purposeId is required"),
    description: z.string().trim().max(5000).optional(),
    price: z.number().positive("Price must be greater than 0"),
    priceUnit: z.nativeEnum(PriceUnit).default(PriceUnit.TOTAL),
    carpetArea: z.number().positive().optional(),
    builtUpArea: z.number().positive().optional(),
    superBuiltUpArea: z.number().positive().optional(),
    bedrooms: z.number().int().min(0).max(20).optional(),
    bathrooms: z.number().int().min(0).max(20).optional(),
    balconies: z.number().int().min(0).max(10).optional(),
    floorNumber: z.number().int().min(-2).max(200).optional(),
    totalFloors: z.number().int().min(1).max(200).optional(),
    parking: z.number().int().min(0).max(20).optional(),
    facing: z.nativeEnum(FacingDirection).optional(),
    furnishing: z.nativeEnum(FurnishingType).optional(),
    propertyAge: z.number().int().min(0).max(150).optional(),
    possessionDate: z.string().datetime().optional(),
    reraNumber: z.string().trim().max(60).optional(),
    status: z.nativeEnum(PropertyStatus),
    publishStatus: z.nativeEnum(PublishStatus).default(PublishStatus.DRAFT),
    featured: z.boolean().default(false),
    verified: z.boolean().default(false),
    latitude: z.number().min(-90).max(90).optional(),
    longitude: z.number().min(-180).max(180).optional(),
    metaTitle: z.string().trim().max(160).optional(),
    metaDescription: z.string().trim().max(300).optional(),
    amenityIds: z.array(z.string()).optional(),
    featureIds: z.array(z.string()).optional(),
    agentIds: z.array(z.string()).optional(),
  }),
});

export const propertyUpdateSchema = z.object({ body: propertySchema.shape.body.partial() });

export const propertyPublicQuerySchema = z.object({
  query: z.object({
    page: z.string().optional(),
    limit: z.string().optional(),
    sort: z.enum(["latest", "price_asc", "price_desc", "area_asc", "area_desc"]).optional(),
    purpose: z.string().optional(),
    location: z.string().optional(),
    builder: z.string().optional(),
    project: z.string().optional(),
    propertyType: z.string().optional(),
    category: z.string().optional(),
    bhk: z.union([z.string(), z.array(z.string())]).optional(),
    minPrice: z.string().optional(),
    maxPrice: z.string().optional(),
    minArea: z.string().optional(),
    maxArea: z.string().optional(),
    possession: z.string().optional(),
    amenities: z.union([z.string(), z.array(z.string())]).optional(),
    rera: z.enum(["true", "false"]).optional(),
    furnishing: z.nativeEnum(FurnishingType).optional(),
    status: z.nativeEnum(PropertyStatus).optional(),
    q: z.string().optional(),
    featured: z.enum(["true", "false"]).optional(),
  }),
});
